pipeline {
  agent {
    docker { image 'node:18-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        echo 'Testing whether docker has been run successfully or not'
        sh 'docker -version'
        sh 'node --version'
      }
    }
  }
}
